### ISSUE TITLE
Compiler error due to `structopt` attributes

### ISSUE THREAD

**Issue by fpoli** [TeXitoi/structopt#125]
The latest nightly Rust generates an error when using `#[structopt(..)]` arguments:

```
error[E0658]: The attribute `structopt` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> src/cli.rs:27:5
   |
27 |     #[structopt(long = "graphviz_file")]
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(custom_attribute)] to the crate attributes to enable
```

See https://travis-ci.org/rust-lang-nursery/polonius/builds/405315425 for a full example.

It would be useful to mention in the readme the `#![feature(custom_attribute)]`.

**Comment by TeXitoi** [comment]
Looking at the problem, the bad hint is tracked in https://github.com/rust-lang/rust/issues/52469

I can't find a `#[macro_use]` before your `extern crate structopt` in polonius, and I suspect that's the problem, because the first error is 

```
error: cannot find derive macro `StructOpt` in this scope
  --> src/cli.rs:11:10
   |
11 | #[derive(StructOpt, Debug)]
   |          ^^^^^^^^^
```

I suspect you must add `#[macro_use]` here: https://github.com/rust-lang-nursery/polonius/blob/master/src/lib.rs#L15

Does it fix your problem?

**Comment by fpoli** [comment]
Yes, thanks!
