### ISSUE TITLE
Cannot compile structopt-derive with LTO

### ISSUE THREAD

**Issue by sondr3** [TeXitoi/structopt#147]
I'm trying to compile a program with `RUSTFLAGS="-Ctarget-cpu=native -Clto=thin"` and it seems that you cannot use thinLTO with `structopt-derive`. I get the following errors:

```sh
❯ env RUSTFLAGS="-Ctarget-cpu=native -Clto=thin" CARGO_INCREMENTAL=0 cargo install --path . --force
  Installing git-anger-management v0.4.0 (/Users/sondre/Code/rust/git-anger-management)
  [...]
   Compiling structopt-derive v0.2.12
   Compiling idna v0.1.5
error: cannot prefer dynamic linking when performing LTO

note: only 'staticlib', 'bin', and 'cdylib' outputs are supported with LTO

error: aborting due to previous error

error: Could not compile `structopt-derive`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `git-anger-management v0.4.0 (/Users/sondre/Code/rust/git-anger-management)`, intermediate artifacts can be found at `/Users/sondre/Code/rust/git-anger-management/target`

Caused by:
  build failed
```

Using `env RUSTFLAGS="-Ctarget-cpu=native" cargo install --path . --force` works fine however, I've tried to also use fatLTO and regular LTO and all of them stops at the above point. This isn't a huge deal but I wanted to build some other scripts I have and check their performance but since all of them use structopt I cannot try out thinLTO.

**Comment by hcpl** [comment]
Crates that contain proc macros of all kinds (function-like, attribute, derive) need to have the `proc-macro` crate type (for now, at least; this restriction may be lifted in the future) and the error output says

> note: only 'staticlib', 'bin', and 'cdylib' outputs are supported with LTO

Check out the "Linkage" chapter of Rust Reference for more info: https://doc.rust-lang.org/reference/linkage.html.

**Comment by hcpl** [comment]
Also, if I were to guess the reason your build errors like that then it's thanks to the nature of `proc-macro` crates. Their job is to define functions that accept arbitrary Rust code to generate other Rust code. Those functions are then only called by the compiler to generate code, but are never included in the final library/executable code. That's why LTO is not applicable for `proc-macro` crates --- their code simply doesn't exist in the final form, so nothing to optimize!

**Comment by sondr3** [comment]
That makes sense, this is really uncharted territory for me. You don't happen to know whether there exists a way to tell cargo to ignore `structopt-derive` so that I can still use `--Clto=thin`? Otherwise I'll just close this issue as it is a Rust thing and not structopt :smiley:

**Comment by hcpl** [comment]
Tried to build https://github.com/sondr3/git-anger-management and `cargo rustc --release -- -Ctarget-cpu=native -Clto=thin` works for me. I think there is no easy way to call that with `cargo install` without using RUSTFLAGS (this env variable is kinda dangerous because it injects build flags in an uncontrollable way unlike passing flags to `cargo rustc` after `--`).

So I guess something like this should work:

```sh
cargo rustc --release -- -Ctarget-cpu=native -Clto=thin
cp target/release/git-anger-management ~/.cargo/bin/
```

But this method is inferior to `cargo install` in one way: `cargo` will not track the installed binary, so when you call `cargo uninstall git-anger-management` it won't know what to uninstall. If that functionality is desirable, you will also need to add an entry in `~/.cargo/.crates.toml`:

```toml
[v1]
# ... entries ...
"git-anger-management 0.4.0 (path+file:///Users/sondre/Code/rust/git-anger-management)" = ["git-anger-management"]
# ... more entries ...
```

**Comment by sondr3** [comment]
Alright, awesome, thank you!
