### ISSUE TITLE
Attribute token streams for raw calls (Rust 1.34)

### ISSUE THREAD

**Issue by seritools** [TeXitoi/structopt#178]
Hey, I've just read about token streams being enabled in custom attributes: https://blog.rust-lang.org/2019/04/11/Rust-1.34.0.html#custom-attributes-accept-arbitrary-token-streams

Might be useful for the raw clap calls like `raw(global_settings = "&[AppSettings::DisableVersion]")`

Probably doesn't warrant the version bump I guess, but would be nice to keep in mind for the future.

**Comment by sphynx** [comment]
I've looked at this issue, trying to see if I can find an easy way to handle arbitrary token streams in `structopt` code. I am not an expert in macros, but here is what I've found. Perhaps it can initiate a discussion or help someone else who is also interested in this issue.

### Situation so far

`structopt` uses `syn` crate for parsing token streams. Eventually, attributes from the source code are parsed into lists of [`syn.Attribute`][1]. Then, raw tokens of those attributes are further parsed into so-called `Meta` which happens [here][2] with the function `iterpret_meta` (which is, by the way, deprecated in favour of `parse_meta`)

So, for example if we try to write an attribute like this (without using `raw`):

```rust
#[derive(StructOpt, Debug)]
#[structopt(setting = AppSettings::UnifiedHelpMessage)]
pub struct Opts {
```
We'll get the following error:

```
 invalid structopt syntax: # [ structopt ( setting = AppSettings :: UnifiedHelpMessage )
```
It comes from the fact that `Attribute::interpret_meta` can't handle more complex token streams and thus returns `None`.

### What we can do

1. Change [`MetaNameValue`][3] definition in `syn` to support not only literals, but more complex token streams as well. Or at least to leave the `Value` part unparsed, just raw tokens. That would be sufficient for our case, because we just want to reuse them for generating `clap` definition.

I've looked at [current][4] `syn` code and the list of open issues, it doesn't look like this issue has been raised so far. Perhaps @dtolnay can comment on that. If this feature is useful, I can try to implement it in `syn` and then use in `structopt`.

2. Write a custom token stream parser ourselves, which we can run if `interpret_meta` returns `None`, which is harder.

3. Find another way of parsing tokens into `Meta`-like structure.

Please share your thoughts.

[1]: https://docs.rs/syn/0.15.34/syn/struct.Attribute.html
[2]: https://github.com/TeXitoi/structopt/blob/master/structopt-derive/src/attrs.rs#L162
[3]: https://docs.rs/syn/0.15.34/syn/struct.MetaNameValue.html
[4]: https://github.com/dtolnay/syn/blob/e52022b8a1d311481d10d80f797f026490dd5ab7/src/attr.rs#L433

**Comment by TeXitoi** [comment]
If we want to support this, I think the solution is to create a custom parser using syn. It should not be so complicated as this kind of things are heavily used in custom macros (at least, I've seen that syn try to provide a framework for that).

**Comment by sphynx** [comment]
@TeXitoi Ok, I've implemented a custom `syn`-based parser for `structopt` attributes. I think, it now allows to get rid of `raw` attributes (although I support them for backward compatibility) and use arbitrary tokens in attributes. For example, this now works:

```rust
#[structopt(setting = AppSettings::UnifiedHelpMessage)]
```

as well as this (requires`syn` to be compiled with `full` feature):

```rust
#[structopt(settings = &[AppSettings::UnifiedHelpMessage])]
```

and this:

```rust
pub const MIN_VALUES: u64 = 2;

...

#[structopt(min_values = MIN_VALUES)]
v: Vec<String>,
```

All the existing tests pass, but I need some more time to polish the error reporting. I'll send a pull request when it's ready.
