### ISSUE TITLE
Enum in args doesn't compile

### ISSUE THREAD

**Issue by FrankelJb** [TeXitoi/structopt#230]
I am trying to use structopt to handle enums. I copy [this](https://github.com/TeXitoi/structopt/blob/master/examples/enum_in_args.rs) exactly. Using `clap = "2.21.0" and `structopt = "0.2.18" produces the following output:

```
✔︎ struct_opt (master) ✗ cargo build
   Compiling struct_opt v0.1.0 ($HOME/storage/projects/rust/struct_opt)
error: proc-macro derive panicked
  --> src/main.rs:13:10
   |
13 | #[derive(StructOpt, Debug)]
   |          ^^^^^^^^^
   |
   = help: message: invalid structopt syntax: # [
           structopt ( possible_values = & Baz :: variants (  ) , case_insensitive = true
           ) ]

error: aborting due to previous error

error: Could not compile `struct_opt`.

To learn more, run the command again with --verbose.
```

**Comment by CreepySkeleton** [comment]
@FrankelJb This is because `structopt` is in the process of releasing `3.0` version that has a number of breaking changes, removing `raw` attributes is one of them. `master` branch is essentially `structopt 3.0` alpha and you're looking at example for `3.0` while using `2.*`. In `2.*` you would have do it via `raw` attribute, see [example  for `2.18` here](https://github.com/TeXitoi/structopt/blob/v0.2.18/examples/enum_in_args.rs). Note: you can choose the version you need via git tags.

**Comment by FrankelJb** [comment]
Thanks for the info, I didnt' realise. Closing as solved
