### ISSUE TITLE
Error messages refer to structopt 3.0

### ISSUE THREAD

**Issue by dtolnay** [TeXitoi/structopt#241]
https://github.com/TeXitoi/structopt/blob/c72ad2f2a40f319b08b2c90c320a749d91a72b48/structopt-derive/src/parse.rs#L74

https://github.com/TeXitoi/structopt/blob/c72ad2f2a40f319b08b2c90c320a749d91a72b48/structopt-derive/src/parse.rs#L133

https://github.com/TeXitoi/structopt/blob/c72ad2f2a40f319b08b2c90c320a749d91a72b48/structopt-derive/src/parse.rs#L157

These errors are confusing because structopt is currently on version 0.3.

**Comment by CreepySkeleton** [comment]
This messages are intentional - they are meant to help people move from 0.2 to 0.3. For example, let's take `raw attrs are deprecated` message - in 0.2 there were magical `raw` attributes, they are gone in 0.3 by a user could accidentally try to use it just because they used to. We emit explicit error that explains the reasoning instead of generating `Arg::raw` method call with wrong arguments. The story is similar for other messages.

Any propositions on smoothing migrating experience are appreciated.

**Comment by dtolnay** [comment]
That's fine, but the error messages should say 0.3, not 3.0.

**Comment by CreepySkeleton** [comment]
Dammit. I *knew* I missed something
