### ISSUE TITLE
v0.3 support for Option<Vec<T>>

### ISSUE THREAD

**Issue by ryankurte** [TeXitoi/structopt#285]
hey thanks for making a super useful crate!

i've just updated from v0.2.x to v0.3.x and am running into a problem with parsing vectors that i'm not sure how to resolve.

In `v0.2.x` the following is valid, and passing an option `-d something` ends up with a vector containing `something`.
```rust
#[derive(Debug, Clone, PartialEq, StructOpt)]
pub struct Options {
    #[structopt(short = "d", long = "data", parse(from_str = "data_from_str"))]
    /// Data as a string
    pub data: Option<Vec<u8>>,
}

pub fn data_from_str(s: &str) -> Vec<u8> {
    s.as_bytes().to_vec()
}
```

In `v0.3.x` this results in an error from structopt derive
```rust
#[derive(Debug, Clone, PartialEq, StructOpt)]
pub struct Options {
    #[structopt(short = "d", long = "data", parse(from_str = data_from_str))]
    /// Data as a string
    pub data: Option<Vec<u8>>,
}

pub fn data_from_str(s: &str) -> Vec<u8> {
    s.as_bytes().to_vec()
}
```

```
error[E0308]: mismatched types
 --> src/main.rs:8:15
  |
8 |     pub data: Option<Vec<u8>>,
  |               ^^^^^^ expected u8, found struct `std::vec::Vec`
  |
  = note: expected type `std::vec::Vec<u8>`
             found type `std::vec::Vec<std::vec::Vec<u8>>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `current`.

To learn more, run the command again with --verbose.
```

is it still possible to achieve this in `v0.3.x`?

**Comment by CreepySkeleton** [comment]
This is because `Option<Vec<T>>` [is a special case now](https://github.com/TeXitoi/structopt/blob/master/CHANGELOG.md#support-optional-vectors-of-arguments-for-distinguishing-between--o-1-2--o-and-no-option-provided-at-all-by-sphynx-180), it's different from `Option<T>`.

To suppress this special casing you can use a type alias, like described in changelog
```rust
type Something = Vec<u8>;

#[derive(StructOpt)]
struct Opt {
    #[structopt(short = "d", long = "data", parse(from_str = data_from_str))]
    /// Data as a string
    pub data: Option<Something>,
}
```

`structopt` doesn't know anything about `Something` so it'll be counted as `Option<T>`, just like in `structopt v0.2`.

Also, pay attention that you don't need `#[structopt(short = "d")]` anymore, use `#[structopt(short)]` instead, the option's name will be deduces from the field. The same applies to `long`. Take a look at [the docs](https://docs.rs/structopt/0.3.5/structopt/#specifying-argument-types).

**Comment by ryankurte** [comment]
Ahh that's the one, thanks!
