### ISSUE TITLE
Stabilize `StructOptInternal` so `StructOpt` is available to be implemented manually

### ISSUE THREAD

**Issue by nagisa** [TeXitoi/structopt#317]
As per [this thread on reddit](https://www.reddit.com/r/rust/comments/efi4kb/who_else_depends_on_structopts_internal_api/fc0w1cu?utm_source=share&utm_medium=web2x) there’s intent to make public API version of `augment_clap`, but I don't believe I've seen an issue to that effect.

Alternatively `derive(StructOpt)` should support generics (i.e. the issue referenced in that thread should be reopened).

**Comment by CreepySkeleton** [comment]
Yeah, I didn't bother to stabilize `augment_clap` just because nobody came here and asked "please do that" so I thought that nobody's really interested.

I agree we need to allow people implementing `StructOpt` manually; the question here is what the API should look like? 

We want to
* leave enough of elbow room for ourselves so we are able to implement new features (i.e the API must be expandable).
* make the API forward compatible, the code that have been working prior to the introducing of a new feature must continue to work properly. Should a user wish to use the new feature, they will be required to tweak their code (naturally).

I propose, after we have #314 landed:
* rename the `StructOptInternal` trait to `StructOptMachinery`  (the name is subject for bikeshedding).
* the new trait will become public, the methods will be set in stone.
* each of the methods must have a sensible default implementation (i.e works in most cases but not guaranteed to work in some of them). Default implementations are set in stone.
* users are free to re-implement the methods as they see fit,  `derive(StructOpt)` is free to re-implement the methods the way it wants.
* should we want a new feature that is not covered by the API existing at the moment, we can add new methods that have a default implementation that works in terms of the old API (i.e the default impl must be backward compatible, but not required to support the new feature). `derive(Structopt)` will re-implement it as required to support the new feature.

To everyone interested: you are free and *encouraged* to participate in the discussion. cc @TeXitoi 



> Alternatively `derive(StructOpt)` should support generics (i.e. the issue referenced in that thread should be reopened).

Like I said, I likely won't get to it on my own in foreseeable future. I'm reopening that issue and going to leave detailed description of the way we want it to be implemented. Such a PR will be accepted.

**Comment by TeXitoi** [comment]
This is an enhancement, and structopt is now feature frozen.
