### ISSUE TITLE
Q: How to re-export structopt from my crate?

### ISSUE THREAD

**Issue by cecton** [TeXitoi/structopt#339]
I have a lib that is using structopt and I would like to re-export it. Unfortunately it seems I can't do that because the macros are not reexported too:

In crate A:
```rust
pub use structopt::{StructOpt, clap};
```

In crate B:
```rust
use a::StructOpt;
```

But I get this compilation error:

```
   Compiling a v2.0.0 (...)
error[E0433]: failed to resolve: could not find `structopt` in `{{root}}`
  --> src/cli.rs:25:24
   |
25 | #[derive(Clone, Debug, StructOpt)]
   |                        ^^^^^^^^^ could not find `structopt` in `{{root}}`
```

**Comment by CreepySkeleton** [comment]
This is one of the core problems with proc-macros. Structopt generates something like this:
```rust
::structopt::StructOpt::some_method(whatever)
```
You see? It assumes that your crate depends on `structopt`, e.g  `::structopt` is a valid path. 

It has to do that because there's no guarantee that you `use structopt::StructOpt as StructOpt;`, you can very well rename this import (and some actually do). The "full path" approach proved least erroneous.

As any heuristic, it has it's own drawbacks, one of them being that you can't simply reexport the trait.  This `B` crate has to depend on structopt too, this is the only way for now. (Keep in mind that the versions must match or [bad things will happen](https://github.com/TeXitoi/structopt/issues/315#issuecomment-568502792))

We would accept a PR that implements this serde-like approach (yes, serde has the very same problem):
```rust
#[derive(StructOpt)]
#[structopt(crate = a::structopt)] // explicitly provide the path for structopt
struct Opt {}
```

**Comment by cecton** [comment]
Inactive, closing

**Comment by kszela24** [comment]
Can we reopen this?  I'd like to contribute this sometime soon to make a crate I've developed work without requiring others to explicitly specify `structopt` as a dependency.  I'm running into the same issue mentioned here with: https://github.com/kszela24/clickrs
