### ISSUE TITLE
Make verbatim_doc_comment the default?

### ISSUE THREAD

**Issue by zhaojiangbin** [TeXitoi/structopt#343]
Thanks for the library.

The `verbatim_doc_comment` attribute is a great feature. It makes the doc comment "what I see is what I get" as help text. But the current implementation requires to have the attribute for every single field, in addition to the containing struct. Wouldn't it be even better to make this attribute the default?

**Comment by CreepySkeleton** [comment]
You're welcome!

No offense, but this is the only the second WISIWIG request so far. The default case is aimed for most users and it looks like almost everybody out there is satisfied with the current implementation; not to mention that such a change would be breaking. We don't really consider new 0.4 release a possibility since we're working on integrating structopt directly into clap.

I don't think we should make it default, but you are very welcome - and encouraged - to open an issue in the https://github.com/clap-rs/clap/ repo. I think some form of fine-grained control via `#[structopt{doc_comment(global, verbatim, keep_trailing_lines, etc)]` would be a descent compromise.

**Comment by zhaojiangbin** [comment]
No worries about closing the issue. 

To me a control such as `#[structopt{doc_comment(global, verbatim, keep_trailing_lines, etc)]` would be sufficient. Looking forward to that.
