### ISSUE TITLE
gen_completion breaks for zsh when using `conflicts_with`

### ISSUE THREAD

**Issue by Nukesor** [TeXitoi/structopt#347]
Hi!

First of all, thanks for providing this awesome library. Writing command line interfaces has never been so convenient!

When building auto completions, I stumbled upon a bug.
It looks like any usage of `conflicts_with` will break zsh completions.
I boiled my use case down to a very simple minimal example project:  
https://github.com/Nukesor/debug/blob/master/src/main.rs
```
use ::structopt::StructOpt;
use ::structopt::clap::Shell;

#[derive(StructOpt, Debug)]
#[structopt()]
pub struct Opt {
    #[structopt(short, long, conflicts_with("task_id"))]
    wait: bool,

    #[structopt()]
    task_id: i32,
}


fn main() {
    let mut clap = Opt::clap();

    let completion_dir = "./";
    let bin_name = "pueue";
    clap.gen_completions(bin_name, Shell::Zsh, completion_dir);
}
```

A pastebin with the stacktrace can be found over here:
https://pastebin.com/UybTmQGB

However, all other completions work like a charm

Structopt version: 0.3.9

**Comment by Nukesor** [comment]
I just tried to reproduce it with clap only, but I'm missing something:
```
use ::clap::{Arg, App, Shell};

fn main() {
    let mut app = App::new("Test")
        .arg(Arg::with_name("test"))
        .arg(Arg::with_name("another")
            .short("a")
            .long("another")
            .conflicts_with("test")
        );

    let completion_dir = "./";
    let bin_name = "pueue";
    app.gen_completions(bin_name, Shell::Zsh, completion_dir);
}
```

This seems to work

**Comment by TeXitoi** [comment]
task_id, as not wrapped in an option, is required. Thus your clap version is different.

Didn't look close, but in this case, wait is never usable, and it can be a case that make the gen completion crash.

**Comment by Nukesor** [comment]
This is weird.

How can one design this use case?

Right now I have this:
```
        #[structopt(short, long, conflicts_with("task_ids"))]
        all: bool,

        #[structopt(required_unless("all"))]
        task_ids: Vec<usize>,
```

Defining `task_ids` as an `Option<Vec<usize>>` results in this error:   
`Option<Vec<T>> type is meaningless for positional argument`

However, that's exactly what I want. A potentially unnecessary positional argument.

I'm Using clap 2.33 (including the clap example above).

**Comment by CreepySkeleton** [comment]
@Nukesor Potentially unnecessary positional arg is written as `Option<T>`. Potentially unnecessary positional arg that potentionally takes multiple values is written as `Vec<T>`.

`Option<Vec<T>>` should be used when you need to distinguish between the following:
* `<no option at all>` => `None`
* `--foo` => `Some(vec![])`
* `--foo a b c` => `Some(vec!["a", "b", "c"])`

That is, when "option with no values" and "no option at all" are not the same.

As you can see, this applies only to non-positional args since positional args ether present and have at least one value, or not present at all; the second "present but has no values" case is impossible. This is why we have this check.

**Comment by Nukesor** [comment]
Ok. Thanks for your explanation!

I think I finally understand the problem.
