### ISSUE TITLE
Improve support for options with multiple values

### ISSUE THREAD

**Issue by zroug** [TeXitoi/structopt#349]
It would be good if StructOpt would make it easier to have options that take multiple values, like for example `--range min max`. Currently this is achievable by using a `Vec<_>` with the `number_of_values` option:
```rust
#[derive(StructOpt)]
struct Args {
    #[structopt(long, number_of_values = 2)]
    range: Vec<u32>
}
```

This works:
```
program --range 1 10 
 => [1, 10]
```

But the default settings are not very good for this use case because this works too, which is unintended:
```
program --range 1 --range 10 
 => [1, 10]
program
 => []
```

The workaround is to also set `required` and `multiple` when `number_of_values` is used and it would be good if that would be the default:
```rust
#[derive(StructOpt)]
struct Args {
    #[structopt(long, number_of_values = 2, required = true, multiple = false)]
    range: Vec<u32>
}
```

Of course it would be even better if fixed sized arrays or tuples with different value types would be supported directly:
```rust
#[derive(StructOpt)]
struct Args {
    #[structopt(long)]
    range: [u32; 2]
}

#[derive(StructOpt)]
struct Args {
    #[structopt(long)]
    range: (u8, u64)
}
```

**Comment by CreepySkeleton** [comment]
There are multiple ways to define "options that take multiple values", like "any number of values" or "from N to M" or "more than N" or whatever. These conditions can be pretty complicated, and `structopt` implements the most relaxed one (any number of values) by default because it's easier to add or change restrictions than to remove them, in `clap` at least.

> The workaround is to also set `required` and `multiple`

This is not a workaround but rather the intended way to do what you want because `required` is set to `false` but default. Also you don't need `multiple` since `structopt` sets it for `Vec<T>`, see [the table](https://docs.rs/structopt/0.3.9/structopt/index.html#type-magic).

Your "fixed arrays" proposal looks interesting, I'm forwarding it to clap (we're working on integrating `structopt` into `clap` as `clap_derive`). If enough people show interest, we'll implement it.

I think this explains your question so I'm closing the issue, feel free to reopen.
