### ISSUE TITLE
Safer environment variables

### ISSUE THREAD

**Issue by Svedrin** [TeXitoi/structopt#370]
I have a question about the environment variable feature. First of all let me say I love structopt, it's just what I've been looking for :slightly_smiling_face:

I think it would be desirable to prefix environment variable names with the project name though. So instead of `ALLOWED_USERS`, have it named `FOOPROJECT_ALLOWED_USERS`. This would enable sanity checking: If I were to erroneously name the variable `FOOPROJECT_USERS` when starting my container, structopt would be able to tell me "hey, you've set a variable there that's unknown, please fix it", instead of just defaulting to an empty ACL and ignoring that unrecognized variable.

Thoughts?

**Comment by CreepySkeleton** [comment]
You know, the request is not without some usefulness, I'll give you that, but still a very weird and niche one.

I don't like the idea of rejecting environment variables that does not belong to the program. I my (subjective) experience, I never saw a program that does something similar, did you?

You can do it without structopt: iterate through `std::env::vars`, filter those starting with `FOOPROJECT_`, check if they are valid.

If it was only up to me, I would have closed it because it kind of goes against my user experience, but let's hear out @TeXitoi first.

**Comment by Svedrin** [comment]
@CreepySkeleton I did indeed: DroneCI once renamed the variable that is used to restrict it to certain users, rather than being open to the whole world. I didn't know that and thought I had restricted it to a certain set of users, but indeed it was wide open. I really wished it did validate the env vars like I propose here at that point. :stuck_out_tongue:

**Comment by CreepySkeleton** [comment]
@TeXitoi gentle ping

**Comment by TeXitoi** [comment]
If the answers is adding prefix automatically, It would break existing program and be confusing.

If not, I don't understand the feature request, you can always prefix by hand.

**Comment by CreepySkeleton** [comment]
Well, I don't see why this should be a part of structopt either. Sorry.

**Comment by Veetaha** [comment]
@TeXitoi @CreepySkeleton let me better formulate the feature request.
To my subjective point of view, it is common to prefix the environment variables with the project name (possibly shortened) so that they don't clash with other env variables (especially if they use some generic wordings like `users: String`, `home: String`, `path: String` in structopt's args delcration).

### Examples:
[`rust-analyzer`](https://github.com/rust-analyzer/rust-analyzer/pull/4424) looks for `RA_LOG` var,
[`rustc`](https://internals.rust-lang.org/t/rust-log-vs-rustc-log/4297) looks for `RUSC_LOG` var,
[`sccache`](https://github.com/mozilla/sccache#storage-options) looks for  `SCCACHE_ENDPOINT`, `SCCACHE_CACHE_SIZE`, `SCCACHE_REDIS` and other....

### Proposal:
Add `env_prefix` option:
```rust
#[derive(StructOpt)]
#[structopt(env_prefix="SCCACHE_")]
struct Args {
    #[structopt(env)]
    endpoint: url::Url
    #[structopt(env)]
    cache_size: u64,
    #[structopt(env)]
    cache_redis: url::Url,
}
```
With this option `structopt` will look for env vars with the same names as `Args` property names but prefixed with what is passed to `env_prefix`.

What do you guys think?

**Comment by CreepySkeleton** [comment]
>Maybe to make it more flexible we could expose env_with = "postprocessing_fn"
where postprocessing_fn is FnOnce(String) -> String which can apply some custom logic for changing the environment varible names.

Couldn't think of a single use of it rather than a string literal. Can you? 

Actually, the env prefix has the same problem as #114 - we can't do that unless it's supported in clap directly.

See https://github.com/TeXitoi/structopt/issues/114#issuecomment-533780498 and https://github.com/TeXitoi/structopt/issues/114#issuecomment-568012331 and now imagine that one of the fields is flatten.
