### ISSUE TITLE
Clarify behaviour of from_iter regarding the first element

### ISSUE THREAD

**Issue by dbdr** [TeXitoi/structopt#380]
When using from_args, the first argument is of course the executable name. When using StructOpt::from_iter, it was not clear to me if the first element would be treated in the same way or not (it seems it is). I'm not sure what the "best" behavior would be, both might be surprising to some users. In any case I think it would be useful to mention this aspect in the doc of from_iter, especially since the first argument has not been parsed as an option might lead to silently not behaving as the user expects.

**Comment by CreepySkeleton** [comment]
`structopt` works on top of [`clap`](https://github.com/clap-rs/clap/). The arguments are passed straight to 
[`App::get_matches_from_safe`](https://docs.rs/clap/2.33.0/clap/struct.App.html#method.get_matches_from_safe), which expresses this behavior rather well:

> NOTE: The first argument will be parsed as the binary name unless AppSettings::NoBinaryName is used

Moreover, many command line parsers work the same way: they expect the first argument to be the name of the executable unless explicitly specified otherwise. But yes, this may confuse  some newcomers, and this is why we have the documentation to point to.

I will attach the note to the methods in question. Well spotted!

**Comment by dbdr** [comment]
Great, thanks a lot for your amazing work!
