### ISSUE TITLE
Handling of multiple named options easily misused

### ISSUE THREAD

**Issue by sourcefrog** [TeXitoi/structopt#396]
I converted some code (in https://github.com/sourcefrog/conserve/commit/7ddb02d0cf47467f1cccc2dcdedb005e8c4e3f25) from clap to structopt, and it generally went well, but there was one thing about the structopt API that led me to introduce a bug.

Originally I wrote:

    #[structopt(long, short)]
    exclude: Vec<String>

The problem is that this leads it to swallow any positional arguments that come after the first `--exclude`. Some programs have that behavior but it seems like not generally what people would want.

I see https://docs.rs/clap/2.33.1/clap/struct.Arg.html#method.multiple has some warnings about this, basically that you should set `Arg::number_of_values(1)` to avoid it. With that added to the structopt attribute, it works as expected. 

It seems like a bit of a trap in structopt though, so could I suggest:

* At least, add an analogous warning to the description of parsing of `Vec<T>`
* Maybe, turn `Vec` into `Arg::number_of_values(1)` by default, and *not* `multiple(true)`, unless the user really indicates they want it to swallow the rest of the arguments. That would be a breaking change though.
* Something else?

**Comment by TeXitoi** [comment]
Yep, it follows clap default, that is quite questionable in this case.

I'll accept a PR that improve the doc, feel free to propose!

We can't change this behavior without a breaking change, and it's likely that structopt will not have a breaking change version as it will be replaced by clap-derive in clap 3 when it's out. So feel free to test with clap 3 beta, and open the corresponding issue if the issue is still here.

**Comment by sourcefrog** [comment]
Thanks for the quick response. That's good to hear about clap-derive and that a new major version might come up over there. I commented on what seems to be the right bug.
