### ISSUE TITLE
Should structopt re-export `paw`?

### ISSUE THREAD

**Issue by epage** [TeXitoi/structopt#407]
`clap-verbosity-flag` is a crate that provides a reusable set of arguments.  When someone tried to use `clap-verbosity-flag` with `paw`, it broke:
```
error[E0433]: failed to resolve: use of undeclared type or module `paw`
  --> /Users/edpage/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-verbosity-flag-0.3.1/src/lib.rs:21:10
   |
21 | #[derive(structopt::StructOpt, Debug, Clone)]
   |          ^^^^^^^^^^^^^^^^^^^^ use of undeclared type or module `paw`

error: aborting due to previous error
```

`structopt` has the `paw` feature on but the symbol `paw` isn't visible within `clap-verbosity-flag` to be able to compile.

Currently structopt re-exports clap.  Should it also re-export paw?

**Comment by CreepySkeleton** [comment]
I say we can gate the reexport under `cfg(feature = "paw")`.

**Comment by CreepySkeleton** [comment]
Wait, we can't reexport it because, astonishingly, *`structopt` doesn't depend on in* 😮 We just [generate some extra code](https://github.com/TeXitoi/structopt/blob/e47d78ccdbab0c58182d941a086eb822192194af/structopt-derive/src/lib.rs#L731-L742) when the `paw` feature is enabled, and that about it :)

On the other hand, if the end user of your crate enabled the feature, they depend on paw already, and we _can_ depend on it without extra trouble.

@TeXitoi what do you think about it?

**Comment by CreepySkeleton** [comment]
Fat chance.

```
Caused by:
  Features and dependencies cannot have the same name: `paw`
```

We can't depend on paw because we have a feature named `paw`, so `paw` is off-limits dependency for us. We can't rename the feature because it's API contract. We can't just get rid of the feature and rely on the implicit feature the `paw` dependency would introduce because implicit features cannot enable other features (we need it to enable `structopt_derive/paw`). If we can't depend on it, we can't reexport it. If we can't reexport it... You get the idea.

I'm afraid this is just unsolvable with no hope on horizon, so I think the only solution is to avoid using the feature. IMHO, it doesn't have any value except giving you warm nostalgic feelings from good old C days when you got the args passed directly to main.

**Comment by CreepySkeleton** [comment]
I did it!
