### ISSUE TITLE
[BUG] False double declaration

### ISSUE THREAD

**Issue by somehowchris** [TeXitoi/structopt#417]
Hey there,

I started a project to port the elasticdump tooling from JS to rs (at least the tooling behind it and not the user provided scripts). I started off by putting all the params inside one struct which was quickly bloated but worked so far. Then I moved on an created different rs files for the input and output parts. From then on i used the `#structopt(flatten)` inside the main opt struct and that lead to that the input and output params weren't really recognized.

[Definition of the main struct](https://github.com/somehowchris/elasticdump-rs/blob/master/packages/elasticdump/src/main.rs)

If I provide `-o` and `-i` it tells me that `--input` has been provided twice. 

```
error: The argument '--input <destination>' was provided more than once, but cannot be used multiple times
```
If I enable the debug mode input and output seem to be the same.
```
Opt { input: InputOpt { destination: "https://localhost:9200", index: "all", transport: None }, output: OutputOpt { destination: "https://localhost:9200", index: "all", transport: None }, elasticsearch: ElasticsearchOpt { headers: "{\"User-Agent\": \"elasticdump\"}", params: None, search_body: None, search_with_template: false, scroll_id: None, scroll_time: { unit: minute, amount: 10 }, no_refresh: false }, aws: AwsOpt { aws_region: None, url_regex: ^https?:\.*.amazonaws.com.*$, chain: None, access_key_id: None, secret_access_key: None, ini_file_profile: None, service: None }, overwrite: false, limit: 100, size: 0, concurrency: 1, concurrency_interval: 5000, interval_cap: 5, carryover_concurrency_count: true, throttle_interval: 1, debug: false, quiet: false, type: Data, delete: false, source_only: false, ignore_errors: false, max_sockets: 340282366920938463463374607431768211455, timeout: None, offset: 0, to_log: true }
```

The input and output struct are defined differently and different short and long values are provided. Am I missing something?

**Comment by CreepySkeleton** [comment]
Would you kindly put together a minimal reproducer (a reasonably short program consisting of a number of `StructOpt` structs and main function using `from_iter`) and paste it here? Just a link to your project won't do because, forgive me for saying so, I'm not very motivated in digging through some project that spans over multiple files just to figure out what the error is - which is likely you're just misusing flatten and it doesn't report it as error.

Based on you description alone, my gut feeling would be that you have fields with the same name in both `InputOpt` and `OutputOpt`. That leads to them having the same identifiers (names) that confuses underlying clap. You may need to make use of `#[structopt(name = "unique_name")]` to sort it out manually.

**Comment by somehowchris** [comment]
Hey man, thanks for the help. Though I gave that a shot but git showed me that I gave the struct a name via the name variable and I though that would be appended through the flattening (feeling stupid right now about assuming that).

After adding a name to each field it ran as usual
