### ISSUE TITLE
Why do the `try_` string parsers run in 2-passes

### ISSUE THREAD

**Issue by JakeDawkins** [TeXitoi/structopt#449]
This is more of a question than a bug. I'm trying to understand why the `try_*` custom string parsers work in a 2-pass manner. 

I was trying to build a string parser that reads from `stdin`, but since that's a side-effect and stdin was getting flushed during the validation pass, that info isn't available in the 2nd pass of the parser. This makes sense, given the "side-effect-free" rule, but I guess I'm not understanding why this is a requirement to begin with.

Since the `try_*` parsers return a `Result` to begin with, why can't they run in a single pass?

Thanks for the help & background! :)

**Comment by TeXitoi** [comment]
That's a technical detail in using clap: clap provide validators, that check the validity of the value by calling a function, and then expose strings, that are then transformed. Using the same function in structopt allow for simplicity, at the cost of double call.

But why would a deserialization method read to stdin? That's quite strange.

**Comment by JakeDawkins** [comment]
Thanks for the response @TeXitoi! I'll close, since that makes sense. 

And yeah, reading stdin in a parser is probably _not_ the most idiomatic thing 🙃 

We had a `--schema` flag, whose value can either be a filepath like `./schema.graphql` or a `-` to signify stdin. We were trying to use a parser to load the contents of _either_ the file or stdin, so the commands themselves didn't have to worry about _where_ the contents were coming from. 

But like I said, that's probably not the most idiomatic way of going about that 😂

**Comment by CreepySkeleton** [comment]
To expand a bit on @TeXitoi's answer, our hands are tied by `clap`'s API. 

Clap has a builtin facility for validating values of arguments that structopt has to use. You specify a closure that should try and validate the argument, whether it meets a certain criteria, and describes what's wrong if it doesn't (error reporting); in rust speak, `Fn(&str) -> Result<(), Error>`. This facility cares only whether the value is valid or not: it's a check, not a transformation.

With structopt, it's different. There's an "output type" for every argument that takes value[s]. It must be constructed form `&str` (or `OsStr`, but everything I say applies to both), and it must be preserved, in rust speak, `Fn(&str) -> Result<T, Error>`. *This is different from what clap expects*. Now we have a structopt-style validator, and we must pass it to clap somehow. What do we do? Well, this:
https://github.com/TeXitoi/structopt/blob/8bda3b64daf53f0ed6bb6bee2c767a63c7c477fc/structopt-derive/src/lib.rs#L154-L158

Yes, the value is simply dropped, because clap provides no way to preserve it. This is why it runs twice: the first time by clap itself, and the second time when building a struct from `ArgMatches`.

---

Let's wander off to a land of dreams: the land where all wars are history, all politicians are competent, all sausage is made of meat and not of toilet paper. In this perfect world, the clap-structopt symbiosis has to live up to the high standard of perfection. Suppose there's a special validation facility, one using [dynamic dispatch](https://doc.rust-lang.org/std/any/trait.Any.html) to store the vals in a heterogeneous container:
```rust
use std::any::Any;

type Error = String;

struct Arg {
    typed_validator: Box<dyn Fn(&str) -> Result<dyn Any, Error>>
}

impl Arg {
    fn typed_validator<T, F>(self, f: F) -> Self
    where 
        F: Fn(&str) -> Result<T, Error>;
}

impl ArgMatches {
    fn get_parsed_values<T>(&mut self, key; &str) -> Result<impl Iterator<Item=T>> {
        self.stored_vals[key].into_iter()
            .map(|any| any.downcast::<T>().expect("invalid type"))
            .collect()
    }
}
```

Now, all that structopt has to do is to make sure that the type used for validator construction and value extraction is the same...  ̵̛̮͔̳̒̚t̸̟̾̏̂͆́ḩ̶̦̜̘̪̚e̶̬͛̓ ̵̧̩̭̔͝s̵͔͛ä̸̹́͗m̴̹̈́e̸̲͋͒̎̄̀.̵̺͐͊.̵̛͙̻̀́̏.̶͈̯̇͆

---

Wake up, Neo. Welcome to the real world.

```
error[E0277]: the size for values of type `(dyn Any + 'static)` cannot be known at compilation time
   --> src/lib.rs:6:22
    |
6   |     typed_validator: Box<dyn Fn(&str) -> Result<dyn Any, Error>>
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `(dyn Any + 'static)`
```

The problem here is that the return type of a function must be sized. And `dyn Trait` is never sized, ergo `Result<dyn Trait, Error>` is not sized either. Even this can be sidestepped: we could `Box` up the return value. Which would eliminate any gains you've taken by excluding the second pass. The question of why the sausage is so crappy must have something to do with it.

---

Anyway, how big these gains might be? At this point, I'm kinda tired of writing this comment and a bit disappointed that my genius design didn't work out, so instead of conducting yet another experiment, I'm going to point out that you do command line parsing once per program run, and also validators tend to be very very cheap performance-wise. It's `O(1)`, so don't think about it unless your profiler points you at the CLI parser (it won't).

**Comment by JakeDawkins** [comment]
😂 Thank you @CreepySkeleton! It's a pleasure reading your responses to issues these days
